config/routes.rb
Rails.application.routes.draw do
  resources :empresas do
    member do
      get :agregar_usuario
      post :crear_usuario
    end
  end
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :users, :except => ['show', 'edit', 'update', 'destroy'] do
    resources :simulacions do
      get '/marcar-realizada', to: "simulacions#marcar_realizada", as: "marcar_realizada"
    end
    get '/encuesta_inicial', to: "users#encuesta_inicial", as: "encuesta_inicial"
    post '/encuesta_inicial', to: "users#submit_encuesta_inicial", as: "submit_encuesta_inicial"
    get '/encuesta_final', to: "users#encuesta_final", as: "encuesta_final"
    post '/encuesta_final', to: "users#submit_encuesta_final", as: "submit_encuesta_final"
  end

  get "user/:id", to: "users#show", as: 'show_user'
  get "user/:id/editar", to:"users#edit", as: 'edit_user'
  post "user/:id/editar", to:"users#update", as: 'update_user'
  delete "user/:id/destroy", to:"users#destroy", as: 'destroy_user'
  

  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  get 'experience', to: "pages#experience"
  get 'microagresiones', to: "pages#microagresiones"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"


  #API
  get "api/show_user/:id", to: "api#show_user", as: "api_show_user"
  post "api/simulacion_realizada/:id", to: "api#simulacion_realizada", as: "api_simulacion_realizada"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :empresa, class_name: "empresa", foreign_key: "empresa_id", optional: true
  has_one :encuesta_inicial, dependent: :destroy
  
  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :telefono, presence: true, numericality: { only_integer: true}, length: {minimum:9, maximum:9}
  validates :encargado, presence: false
  validates :admin, presence: false

  def has_simulacion?
    simulacion = Simulacion.where(user_id: self.id).all
    if simulacion.empty?
      false
    else
      true
    end
    
  end

  def simulaciones
    Simulacion.where(user_id: self.id).all
  end

  def simulaciones_realizadas
    Simulacion.where(user_id: self.id).where(realizada: true).all
  end

  def simulaciones_pendientes
    Simulacion.where(user_id: self.id).where(realizada: false).all
  end

  def empresa
    Empresa.find(self.empresa_id)
  end

  def empresas
    if self.admin
      Empresa.all
    end
  end

  def encuesta_inicial
    EncuestaInicial.find_by(user_id: self.id)
  end

  def encuesta_inicial?
    if self.encuesta_inicial.nil?
      false
    else
      true
    end
  end

  def encuesta_final
    EncuestaFinal.find_by(user_id: self.id)
  end

  def encuesta_final?
    if self.encuesta_final.nil?
      false
    else
      true
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource

    def show
        @user = User.find(params[:id])

        if @user.simulaciones.first.realizada
            @count = 3
        elsif  @user.encuesta_inicial?
            @count = 2
        else
            @count = 1
        end
        
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(create_params)

        if @user.save
            flash[:notice] = "Usuario modificado con exito"
            redirect_to show_user_path
        else
            flash[:alert] = @user.errors.full_messages.join(', ')
            redirect_to edit_user_path
        end
    end

    def destroy
        @user = User.find(params[:id])
        empresa = Empresa.find(@user.empresa_id)
        name = @user.nombre
        if @user.destroy
            flash[:notice] = "#{name} se ha eliminado con exito"
            redirect_to empresa_path(empresa.id)
        else
            flash[:alert] = "No se pudo eliminar #{name}"
            redirect_to show_user_path
        end
    end

    def encuesta_inicial
        @user = User.find(params[:user_id])
        if @user.encuesta_inicial?
            flash[:alert] = "Ya has realizado la encuesta inicial"
            redirect_to experience_path(user_id: @user.id)
        end
        @encuesta = EncuestaInicial.new()
    end

    def submit_encuesta_inicial
        @user = User.find(params[:user_id])
        if @user.encuesta_inicial?
            flash[:alert] = "Ya has realizado la encuesta inicial"
            redirect_to experience_path(user_id: @user.id)
        end
        @encuesta = EncuestaInicial.new(encuesta_inicial_create_params)
        @encuesta.update(user_id: params[:user_id])

        if @encuesta.save
            flash[:notice] = "Encuesta completada con exito"
            redirect_to experience_path(user_id: @user.id)
        else
            flash[:alert] = @encuesta.errors.full_messages.join(', ')
        end
    end

    def encuesta_final
        @user = User.find(params[:user_id])
        if @user.encuesta_final?
            flash[:alert] = "Ya has realizado la encuesta inicial"
            redirect_to show_user_path(@user.id)
        end
        @encuesta = EncuestaInicial.new()
    end

    def submit_encuesta_final
        @user = User.find(params[:user_id])
        if @user.encuesta_final?
            flash[:alert] = "Ya has realizado la encuesta final"
            redirect_to show_user_path(@user.id)
        end
        @encuesta = EncuestaFinal.new(encuesta_final_create_params)
        @encuesta.update(user_id: params[:user_id])

        if @encuesta.save
            flash[:notice] = "Encuesta completada con exito"
            redirect_to show_user_path(params[:user_id])
        else
            flash[:alert] = @encuesta.errors.full_messages.join(', ')
        end
    end

    private

    def create_params
        params.require(:user).permit(:nombre, :email, :apellido, :telefono, :encargado, :password, :password_confirmation)
      end

    def encuesta_inicial_create_params
        if params.has_key?(:encuesta_inicial)
            params.fetch(:encuesta_inicial)
            .permit(:pregunta1, :pregunta2, :pregunta3, :pregunta4, :pregunta5, :pregunta6)
        end
    end

    def encuesta_final_create_params
        if params.has_key?(:encuesta_final)
            params.fetch(:encuesta_final)
            .permit(:pregunta1, :pregunta2, :pregunta3, :pregunta4)
        end
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/sections/_admin-body.html.erb
<div class="event-schedule-area-two bg-color pad100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title text-center">
                  <h2>Encargados</h2>
                </div>
            </div>
            <!-- /.col end-->
        </div>
        <!-- row end-->
        <div class="row">
            <div class="col-lg-12">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade active show" id="home" role="tabpanel">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th class="text-center" scope="col">Empresa</th>
                                        <th scope="col">Foto</th>
                                        <th scope="col">Contacto</th>
                                        <th scope="col"></th>
                                        <th class="text-center" scope="col">Perfil</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @user.empresas.each do |empresa| %>
                                        <% encargado = empresa.encargados.last%>
                                        <tr class="inner-box">
                                            <th scope="row">
                                                <div class="event-date">
                                                    <h4><%= empresa.nombre%></h4>
                                                </div>
                                            </th>
                                            <td>
                                                <div class="event-img">
                                                    <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" />
                                                </div>
                                            </td>
                                            <td>
                                                <div class="event-wrap">
                                                    <h3><a href="#"><%= "#{encargado.nombre} #{encargado.apellido}"%></a></h3>
                                                    <div class="meta">
                                                        <div class="organizers">
                                                            <a href="#"><%= "#{encargado.email}"%></a>
                                                        </div>
                                                        <div>
                                                            <%= fa_icon('phone') %><a href="#"><%= " +56 #{encargado.telefono[0]} #{encargado.telefono[1,4]} #{encargado.telefono[5,9]}"%></a>
                                                        </div>

                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="r-no">
                                                    <span></span>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="primary-btn">
                                                    <%= link_to "Ver más", show_user_path(encargado.id), class:"btn bg-secondary text-white" %>
                                                </div>
                                            </td>
                                        </tr>
                                    <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /col end-->
        </div>
        <!-- /row end-->
    </div>
</div>

app/views/users/sections/_encargado-body.html.erb
<div class="event-schedule-area-two bg-color pad100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title text-center">
                  <h2>Empleados</h2>
                </div>
            </div>
            <!-- /.col end-->
        </div>
        <!-- row end-->
        <div class="row">
            <div class="col-lg-12">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade active show" id="home" role="tabpanel">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Foto</th>
                                        <th scope="col">Contacto</th>
                                        <th scope="col">Simulacion</th>
                                        <th scope="col">Estado</th>
                                        <th class="text-center" scope="col">Acción</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @user.empresa.empleados.each do |empleado| %>
                                        <%= form_for :simulacion, url: user_simulacions_path(user_id: empleado.id), method: :post do |f| %>
                                            <tr class="inner-box">
                                                <td>
                                                    <div class="event-img">
                                                        <img src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="" />
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="event-wrap">
                                                        <h3><a href="#"><%= "#{empleado.nombre} #{empleado.apellido}"%></a></h3>
                                                        <div class="meta">
                                                            <div class="organizers">
                                                                <a href="#"><%= "#{empleado.email}"%></a>
                                                            </div>
                                                            <div>
                                                                <%= fa_icon('phone') %><a href="#"><%= " +56 #{empleado.telefono[0]} #{empleado.telefono[1,4]} #{empleado.telefono[5,9]}"%></a>
                                                            </div>

                                                        </div>
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="r-no">
                                                        <span>
                                                        <% if !empleado.simulaciones.empty? %>              
                                                            <%= empleado.simulaciones.first.nombre %>
                                                        <% else %>
                                                            <%= f.select :nombre, ["Microinsulto"],{}, class: "form-select" %>
                                                        <% end%>
                                                        </span>
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="r-no">
                                                        <span>
                                                        <% if !empleado.simulaciones.empty? %>              
                                                            <% if empleado.encuesta_final? %>
                                                                Realizada
                                                            <% else %>
                                                                Pendiente
                                                            <% end %>
                                                        <% else %>
                                                                No asignado
                                                        <% end%>
                                                        </span>              
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="primary-btn">
                                                        <% if !empleado.simulaciones.empty? %>
                                                            <%= link_to "Ver más", show_user_path(empleado.id), class:"btn bg-secondary text-white" %>
                                                        <% else%>
                                                            <%= f.submit "Asignar Simulación", class: "btn bg-secondary text-white " %>
                                                        <% end %>

                                                        <%= render 'users/sections/modal-simulacion', empleado: empleado %>
                                                    </div>
                                                </td>
                                            </tr>
                                        <% end %>
                                    <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /col end-->
        </div>
        <!-- /row end-->
    </div>
</div>

app/views/users/sections/_encargado-results.html.erb
<div class='event-schedule-area-two bg-color pad100 mb-4'>
  <div class ="container">
    <% if @user.empresa.promedio_encuesta_inicial != -1 %>
        <h3 class ="mb-3">RESULTADOS DE EMPRESA</h3>
          <table class="table table-bordered result-container2">
            <tbody>
              <tr>
                <td scope="col"><b>Promedio Conocimiento General:</b></td>
                <td scope="col" ><%= "#{@user.empresa.promedio_encuesta_inicial}%"%></td>
              </tr>
              <tr>
                <td scope="col"><b>Promedio Aprendizaje:</b></td>
                <td scope="col" > <%= "#{@user.empresa.promedio_encuesta_final}%"%></td>
              </tr>
              <tr>
                <td scope="col"><b>Tendencia General de Decisiones:</b></td>
                <td scope="col" >
                  <% case @user.empresa.tendencia_decisiones
                    when 0%> 
                    <%= "No interviene"%>
                  <% when 1%>
                    <%= "Intervención Pasiva"%>
                  <% when 2 %>
                    <%= "Intervención Activa"%>
                  <% else%>
                    <%= "No hay datos"%>
                  <% end %>
                 </td>
              </tr>
            </tbody>
          </table>

    <% end %>
  </div>
</div>

app/views/users/sections/_header.html.erb
<div class="col-lg-12 mb-4 mb-sm-5">
  <div class="card card-style1 border-0">
    <div class="card-body p-1-9 p-sm-2-3 p-md-6 p-lg-7">
      <div class="row align-items-center">
        <div class="col-lg-6 mb-4 mb-lg-0">
          <% if @user.admin %>
            <img src="https://bootdey.com/img/Content/avatar/avatar5.png" alt="...">
          <% elsif @user.encargado %>
            <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="...">
          <% else %>
            <img src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="...">
          <% end %>
        </div>
        <div class="col-lg-6 px-xl-10">
          <div class="bg-secondary d-lg-inline-block py-1-9 px-1-9 px-sm-6 mb-1-9 rounded">
            <h3 class="h2 text-white mb-0"><%= "#{@user.nombre} #{@user.apellido}" %></h3>
            <span class="text-badge">
              <% if @user.admin %>
                Admin
              <% elsif @user.encargado%>
                Encargado
              <% else%>
                Empleado
              <% end %>   
            </span>
          </div>
          <ul class="list-unstyled mb-1-9">
            <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">Empresa:</span><%= " #{@user.empresa.nombre}" %> </li>
            <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">Email:</span><%= " #{@user.email}" %> </li>
            <li class="display-28"><span class="display-26 text-secondary me-2 font-weight-600">Phone:</span><%= " +56 #{@user.telefono[0]} #{@user.telefono[1,4]} #{@user.telefono[5,9]}"   %> </li>
          </ul>
          <% if current_user.id == @user.id%>
              <%= link_to "Editar Perfil", edit_user_registration_path(current_user.id), class: 'btn btn-secondary float-end' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/sections/_stepper.html.erb
<h2 class ="text-center">EXPERIENCIA: <%= @user.simulaciones.first.nombre.upcase%> </h2>
<div class="progress-wrapper">
  <div id="progress-bar-container">
    <ul>
      <li class="step step01 active">
        <div class="step-inner">Paso 1</div>
      </li>
      <li class="step step02 <%= @count>=2 ? "active" : "" %>">
        <div class="step-inner">Paso 2</div>
      </li>
      <li class="step step03 <%=@count==3 ? "active" : "" %>">
        <div class="step-inner">Paso 3</div>
      </li>
    </ul>
    <div id="line">
      <div id="<%= 
      if @count== 3
        "line-progress3"
      elsif  @count== 2
         "line-progress2"
      else
        "line-progress"
      end
      %>"></div>
    </div>
    <!-- progress-bar-container -->
    <div id="progress-content-section">
      <div class="section-content step1 <%= @count == 1 ? "active" : "" %>">
        <h2>Cuestionario Inicial</h2>
        <% if current_user.id == @user.id %>
            <% if !@user.encuesta_inicial? %>
            <p>
                Antes de comenzar, porfavor realiza el siguiente cuestionario para poner a prueba tus conocimientos sobre las microagresiones.
                <div>
                    <%= link_to "Comenzar", user_encuesta_inicial_path(@user.id), class: 'btn btn-primary ' %>
                </div>
            </p>
            <% else %>
                Ya completaste el cuestionario inicial, por favor avanza al siguiente paso.
            <% end%>
        <% else %>
            <% if !@user.encuesta_inicial? %>
            <p>
                Este empleado todavía no completa el cuestionario inicial.
            </p>
            <% else %>
                Este empleado ya completo el cuestionario inicial.
            <% end%>
        <% end %>
      </div>
      <div class="section-content step2 <%= @count == 2 ? "active" : "" %>">
        <h2>Realiza la simulación</h2>

        <% if !@user.encuesta_inicial? %>
            Todavía no realizas la encuesta inicial.
        <% elsif @user.simulaciones.first.realizada %>
            <p>
            Ya completaste la simulación, porfavor avanza al siguiente paso.
            </p>
        <% else%>
            <div class ="container">
              <div class = "row">
              <p> Ahora estas preparado para comenzar, procede a experimentar nuestra simulación. </p>
              </div>
              <div class = "row ">
                <div class="col">
                  <%= link_to "Estoy listo",experience_path(user_id: @user.id),  class: "btn btn-primary"%>
                </div>
              </div>
            </div>
            
        <% end %>
      </div>


      <div class="section-content step3 <%= @count == 3 ? "active" : "" %>">
        <h2>Cuestionario Final</h2>
        
        <% if @user.simulaciones.first.realizada %>
            <% if current_user.id == @user.id %>

              <% if @user.encuesta_final?%>
                  Ya completaste el cuestionario final.
              <% else%>
                  <p>
                  Para finalizar, porfavor realiza el siguiente cuestionario para poner a prueba tu aprendizaje sobre las microagresiones.
                  <div>
                      <%= link_to "Comenzar", user_encuesta_final_path(@user.id), class: 'btn btn-primary ' %>
                  </div>
                  </p>
              <% end %>

            <% else %>

              <% if @user.encuesta_final?%>
                  Este empleado ya completo el cuestionario final.
              <% else%>
                  Este empleado debe realizar el cuestionario final para finalizar.

              <% end %>

            <% end %>

        
        <% else %>
            <p>
                Todavía no realizas la simulación.
            </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/sections/_user-body.html.erb
<div class="container">

    <% if @user.encuesta_final? %>
        <h3 class ="text-center mb-4">Resultados</h3>
        <table class="table table-bordered result-container">
          <tbody>
            <tr>
              <td scope="col"><b>Conocimiento General</b></td>
              <td scope="col"><%= "#{@user.encuesta_inicial.porcentaje_bueno}% correcto"%></td>
            </tr>
            <tr>
              <td scope="col"><b>Aprendizaje</b></td>
              <td scope="col"> <%= "#{@user.encuesta_final.porcentaje_bueno}% correcto"%></td>
            </tr>
            <tr>
              <td scope="col"><b>Tendencia de Decisiones:</b></td>
              <td scope="col"> 
              <% case @user.simulaciones.first.decisiones 
                    when 0%> 
                    <%= "No interviene"%>
                  <% when 1%>
                    <%= "Intervención Pasiva"%>
                  <% when 2 %>
                    <%= "Intervención Activa"%>
                  <% else%>
                    <%= "No hay datos"%>
                  <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        

    <% elsif @user.simulaciones.empty?%>
        <h3>Espera a que tu encargado te asigne una simulación</h3>
    <% else %>
        <%= render 'users/sections/user-simulaciones' %>
    <% end %>


</div>

app/views/users/sections/_user-simulaciones.html.erb
<div class="event-schedule-area-two bg-color pad100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title text-center">
                  <h2>Simulaciones Asignadas</h2>
                </div>
            </div>
            <!-- /.col end-->
        </div>
        <!-- row end-->
        <div class="row">
            <div class="col-lg-12">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade active show" id="home" role="tabpanel">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Tipo</th>
                                        <th scope="col">Estado</th>
                                        <th class="text-center" scope="col">Acción</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @user.simulaciones.each do |simulacion| %>
                                            <tr class="inner-box">
                                                <td>
                                                    <div class="r-no">
                                                        <span>
                                                            <%= simulacion.nombre%>
                                                        </span>
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="r-no">
                                                        <span>
                                                            <% if simulacion.realizada %>
                                                                Realizada
                                                            <% else %>
                                                                Pendiente
                                                            <% end %>
                                                        </span>              
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="primary-btn">
                                                        <%= link_to "Ver", experience_path(user_id: @user.id), class: 'btn bg-secondary text-white'%>
                                                    </div>
                                                </td>
                                            </tr>
                                    <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /col end-->
        </div>
        <!-- /row end-->
    </div>
</div>