config/routes.rb
Rails.application.routes.draw do
  resources :empresas do
    member do
      get :agregar_usuario
      post :crear_usuario
    end
  end
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :users, :except => ['show', 'edit', 'update', 'destroy'] do
    resources :simulacions do
      get '/marcar-realizada', to: "simulacions#marcar_realizada", as: "marcar_realizada"
    end
    get '/encuesta_inicial', to: "users#encuesta_inicial", as: "encuesta_inicial"
    post '/encuesta_inicial', to: "users#submit_encuesta_inicial", as: "submit_encuesta_inicial"
    get '/encuesta_final', to: "users#encuesta_final", as: "encuesta_final"
    post '/encuesta_final', to: "users#submit_encuesta_final", as: "submit_encuesta_final"
  end

  get "user/:id", to: "users#show", as: 'show_user'
  get "user/:id/editar", to:"users#edit", as: 'edit_user'
  post "user/:id/editar", to:"users#update", as: 'update_user'
  delete "user/:id/destroy", to:"users#destroy", as: 'destroy_user'
  

  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  get 'experience', to: "pages#experience"
  get 'microagresiones', to: "pages#microagresiones"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"


  #API
  get "api/show_user/:id", to: "api#show_user", as: "api_show_user"
  post "api/simulacion_realizada/:id", to: "api#simulacion_realizada", as: "api_simulacion_realizada"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :empresa, class_name: "empresa", foreign_key: "empresa_id", optional: true
  has_one :encuesta_inicial, dependent: :destroy
  
  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :telefono, presence: true, numericality: { only_integer: true}, length: {minimum:9, maximum:9}
  validates :encargado, presence: false
  validates :admin, presence: false

  def has_simulacion?
    simulacion = Simulacion.where(user_id: self.id).all
    if simulacion.empty?
      false
    else
      true
    end
    
  end

  def simulaciones
    Simulacion.where(user_id: self.id).all
  end

  def simulaciones_realizadas
    Simulacion.where(user_id: self.id).where(realizada: true).all
  end

  def simulaciones_pendientes
    Simulacion.where(user_id: self.id).where(realizada: false).all
  end

  def empresa
    Empresa.find(self.empresa_id)
  end

  def empresas
    if self.admin
      Empresa.all
    end
  end

  def encuesta_inicial
    EncuestaInicial.find_by(user_id: self.id)
  end

  def encuesta_inicial?
    if self.encuesta_inicial.nil?
      false
    else
      true
    end
  end

  def encuesta_final
    EncuestaFinal.find_by(user_id: self.id)
  end

  def encuesta_final?
    if self.encuesta_final.nil?
      false
    else
      true
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource

    def show
        @user = User.find(params[:id])

        if @user.simulaciones.first.realizada
            @count = 3
        elsif  @user.encuesta_inicial?
            @count = 2
        else
            @count = 1
        end
        
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(create_params)

        if @user.save
            flash[:notice] = "Usuario modificado con exito"
            redirect_to show_user_path
        else
            flash[:alert] = @user.errors.full_messages.join(', ')
            redirect_to edit_user_path
        end
    end

    def destroy
        @user = User.find(params[:id])
        empresa = Empresa.find(@user.empresa_id)
        name = @user.nombre
        if @user.destroy
            flash[:notice] = "#{name} se ha eliminado con exito"
            redirect_to empresa_path(empresa.id)
        else
            flash[:alert] = "No se pudo eliminar #{name}"
            redirect_to show_user_path
        end
    end

    def encuesta_inicial
        @user = User.find(params[:user_id])
        if @user.encuesta_inicial?
            flash[:alert] = "Ya has realizado la encuesta inicial"
            redirect_to experience_path(user_id: @user.id)
        end
        @encuesta = EncuestaInicial.new()
    end

    def submit_encuesta_inicial
        @user = User.find(params[:user_id])
        if @user.encuesta_inicial?
            flash[:alert] = "Ya has realizado la encuesta inicial"
            redirect_to experience_path(user_id: @user.id)
        end
        @encuesta = EncuestaInicial.new(encuesta_inicial_create_params)
        @encuesta.update(user_id: params[:user_id])

        if @encuesta.save
            flash[:notice] = "Encuesta completada con exito"
            redirect_to experience_path(user_id: @user.id)
        else
            flash[:alert] = @encuesta.errors.full_messages.join(', ')
        end
    end

    def encuesta_final
        @user = User.find(params[:user_id])
        if @user.encuesta_final?
            flash[:alert] = "Ya has realizado la encuesta inicial"
            redirect_to show_user_path(@user.id)
        end
        @encuesta = EncuestaInicial.new()
    end

    def submit_encuesta_final
        @user = User.find(params[:user_id])
        if @user.encuesta_final?
            flash[:alert] = "Ya has realizado la encuesta final"
            redirect_to show_user_path(@user.id)
        end
        @encuesta = EncuestaFinal.new(encuesta_final_create_params)
        @encuesta.update(user_id: params[:user_id])

        if @encuesta.save
            flash[:notice] = "Encuesta completada con exito"
            redirect_to show_user_path(params[:user_id])
        else
            flash[:alert] = @encuesta.errors.full_messages.join(', ')
        end
    end

    private

    def create_params
        params.require(:user).permit(:nombre, :email, :apellido, :telefono, :encargado, :password, :password_confirmation)
      end

    def encuesta_inicial_create_params
        if params.has_key?(:encuesta_inicial)
            params.fetch(:encuesta_inicial)
            .permit(:pregunta1, :pregunta2, :pregunta3, :pregunta4, :pregunta5, :pregunta6)
        end
    end

    def encuesta_final_create_params
        if params.has_key?(:encuesta_final)
            params.fetch(:encuesta_final)
            .permit(:pregunta1, :pregunta2, :pregunta3, :pregunta4)
        end
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class='container'>
  <h2>Editar Trabajador</h2>
  <br/>

  <%= form_for :user,  url: update_user_path, method: :post do |f| %>
    
    <div class="field">
      <%= f.label :nombre, class: "form-label"%><br />
      <%= f.text_field :nombre, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :apellido, class: "form-label" %><br />
      <%= f.text_field :apellido, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :email, class: "form-label" %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :telefono, class: "form-label" %><br />
      <%= f.text_field :telefono, autofocus: true, autocomplete: "phone" %>
    </div>

    <div class="field">
      <%= f.label :encargado, "Encargado: " %>
      <%= f.check_box :encargado, {:class => "form-check-input"}, 'true', 'false' %>
    </div>
    <br/>

    <div class="actions">
      <%= f.submit "Editar", class: 'btn btn-primary' %>
      <%= link_to "Volver", :back, class: 'btn btn-secondary' %>
    </div>
    <br/>
  <% end %>
</div>

app/views/users/encuesta_final.html.erb
<div class='container'>
    <h1 class="mb-4">Encuesta Final</h1>

        <%= form_for :encuesta_final, url: user_submit_encuesta_final_path, method: :post do |f| %>
            <div class="row">

                <div class="col-12 mb-4">
                    <b>En la simulación evidenciaste un:</b><br/>
                    <%= f.radio_button :pregunta1, true %>    
                    Comentario o acción discriminatoria accidental.
                    <br/>
                    <%= f.radio_button :pregunta1, false %>    
                    Comportamiento intencional y discriminatorio sin pretensión de ofensa.
                    <br/>
                    <%= f.radio_button :pregunta1, false %>    
                    Minimización de experiencias ajenas
                    <br/>
                    <%= f.radio_button :pregunta1, false %>    
                    No hubo ningún comentario o acción inadecuada.
                </div>

                <div class="col-12 mb-4">
                    <b>Teniendo bajo consideración que un(a) <br/>
                    I. Microataque es un comportamiento intencional y discriminatorio sin pretensión de ofensa.<br/>
                    II. Microinvalidación es menospreciar o invalidar experiencias ajenas<br/>
                    III. Microinsulto es un comentario o acción que es discriminatoria accidentalmente.<br/>
                    En la simulación realizada recientemente, usted fue testigo de:

                    </b><br/>
                    <%= f.radio_button :pregunta2, false %>    Solo I
                    <br/>
                    <%= f.radio_button :pregunta2, false %>   Solo II
                    <br/>
                    <%= f.radio_button :pregunta2, true %>   Solo III
                    <br/>
                    <%= f.radio_button :pregunta2, false %>  I, II
                    <br/>
                    <%= f.radio_button :pregunta2, false %>   III, I
                    <br/>
                    <%= f.radio_button :pregunta2, false %>   Ninguna de las anteriores.
                </div>

                <div class="col-12 mb-4">
                    <b>Considera que en la simulación se atacó a:</b><br/>
                    <%= f.radio_button :pregunta3, true %>    Luis.
                    <br/>
                    <%= f.radio_button :pregunta3, false %>    Me sentí atacado durante la simulación.                
                    <br/>
                    <%= f.radio_button :pregunta3, false %>    Leonardo.
                    <br/>
                    <%= f.radio_button :pregunta3, false %>    Laura.
                    <br/>
                    <%= f.radio_button :pregunta3, false %>    No se atacó a nadie durante la simulación.
                </div>

                <div class="col-12 mb-4">
                    <b>¿Alguna vez has visto en lugar de trabajo una situación similar?</b><br/>
                    <%= f.radio_button :pregunta4, true %>    
                    Si
                    <br/>
                    <%= f.radio_button :pregunta4, true %>    
                    No.
                    <br/>
                    <%= f.radio_button :pregunta4, true %>    
                    Quizás.
                    <br/>

                </div>
                
                <div class="mt-3">
                    <%= f.submit "Enviar", class: "btn btn-primary " %>
                    <%= link_to "Volver", :back, class: 'btn btn-secondary' %>
                </div>
            </div>

        <% end %>

    </div>

app/views/users/encuesta_inicial.html.erb
<div class='container'>
    <h1 class="mb-4">Encuesta Inicial</h1>

        <%= form_for :encuesta_inicial, url: user_submit_encuesta_inicial_path, method: :post do |f| %>
            <div class="row">

                <div class="col-12 mb-4">
                    <b>Elige la definición más adecuada para Microagresión</b><br/>
                    <%= f.radio_button :pregunta1, true %>    
                    Una microagresión es un comentario o acción que se dirige negativamente a un grupo de personas marginado.
                    <br/>
                    <%= f.radio_button :pregunta1, false %>    
                    Una microagresión es un comentario accidental que se dirige a personas físicamente diferentes con mala intención.
                    <br/>
                    <%= f.radio_button :pregunta1, false %>    
                    Acción violenta que realiza una persona con la intención de causar un daño a otra.
                </div>

                <div class="col-12 mb-4">
                    <b>¿Cuál de las siguientes alternativas es un tipo de microagresión?</b><br/>
                    <%= f.radio_button :pregunta2, false %>    Microinsulto
                    <br/>
                    <%= f.radio_button :pregunta2, false %>   Microinvalidación
                    <br/>
                    <%= f.radio_button :pregunta2, false %>   Microataque
                    <br/>
                    <%= f.radio_button :pregunta2, false %>  Microdiscriminación
                    <br/>
                    <%= f.radio_button :pregunta2, true %>   Solo a, b y c
                    <br/>
                    <%= f.radio_button :pregunta2, false %>   a, b, c y d
                </div>

                <div class="col-12 mb-4">
                    <b>Microinsulto</b><br/>
                    <%= f.radio_button :pregunta3, true %>    
                    Es un comentario o acción que es discriminatoria accidentalmente.
                    <br/>
                    <%= f.radio_button :pregunta3, false %>    
                    Es una acción agresiva que insulta a otra persona.                
                    <br/>
                    <%= f.radio_button :pregunta3, false %>    
                    Es un comentario o acción que discrimina.
                </div>

                <div class="col-12 mb-4">
                    <b>Un ejemplo de microagresión puede ser:</b><br/>
                    <%= f.radio_button :pregunta4, false %>    
                    Decir “Mi jefa está loca”.
                    <br/>
                    <%= f.radio_button :pregunta4, false %>    
                    Decirle a alguien “Tu nombre es tan difícil de pronunciar”.
                    <br/>
                    <%= f.radio_button :pregunta4, false %>    
                    Interrumpir a alguien mientras habla.
                    <br/>
                    <%= f.radio_button :pregunta4, false %>    
                    Decirle a una persona delgada que debería comer más.
                    <br/>
                    <%= f.radio_button :pregunta4, true %>    
                    Todas
                    <br/>
                    <%= f.radio_button :pregunta4, false %>    
                    Solo a, b y c
                </div>


                <div class="col-12 mb-4">
                    <b>Una definición adecuada del tipo Microataque es</b><br/>
                    <%= f.radio_button :pregunta5, false %>    
                    Es un comentario o acción que es discriminatoria accidentalmente.
                    <br/>
                    <%= f.radio_button :pregunta5, true %>    
                    Comportamiento intencional y discriminatorio sin pretensión de ofensa.
                    <br/>
                    <%= f.radio_button :pregunta5, false %>    
                    Menospreciar o invalidar experiencias ajenas.
                    <br/>
                    <%= f.radio_button :pregunta5, false %>    
                    Decirle a una persona delgada que debería comer más.
                    <br/>
                    <%= f.radio_button :pregunta5, false %>    
                    Acción violenta que realiza una persona con la intención de causar un daño a otra.
                </div>

                <div class="col-12 mb-4">
                    <b>Una definición adecuada del tipo Microinvalidacion es</b><br/>
                    <%= f.radio_button :pregunta6, false %>    
                    Hacer que una persona pierda valor ante otros.
                    <br/>
                    <%= f.radio_button :pregunta6, true %>    
                    Menospreciar o invalidar experiencias ajenas.
                    <br/>
                    <%= f.radio_button :pregunta6, false %>    
                    Es un comentario o acción que es discriminatoria accidentalmente.
                    <br/>
                    <%= f.radio_button :pregunta6, false %>    
                    Comportamiento intencional y discriminatorio sin pretensión de ofensa.
                </div>

                <div class="col-12 mb-4">
                    <b>Alguna vez has visto en lugar de trabajo una situación similar a una microagresión?</b><br/>
                    <%= f.radio_button :pregunta7, false %>    
                    Si
                    <br/>
                    <%= f.radio_button :pregunta7, true %>    
                    No.
                    <br/>
                    <%= f.radio_button :pregunta7, false %>    
                    No estoy seguro/a.
                    <br/>
                    <%= f.radio_button :pregunta7, false %>    
                    Comportamiento intencional y discriminatorio sin pretensión de ofensa.
                </div>
                
                <div class="mt-3">
                    <%= f.submit "Enviar", class: "btn btn-primary " %>
                    <%= link_to "Volver", :back, class: 'btn btn-secondary' %>
                </div>
            </div>

        <% end %>

    </div>

app/views/users/show.html.erb
<section class ="perfil-usuario">
  <div class="container-fluid">
    <div class="row">
    <%= render 'users/sections/header' %>
    </div>
    <div class="row mb-5">
      <% if @user.admin %>
        <%= render 'users/sections/admin-body'%>
      <% elsif @user.encargado %>
      <%= render 'users/sections/encargado-results'%>
        <%= render 'users/sections/encargado-body'%>
      <% else %>
        <%= render 'users/sections/user-body'%>
      <% end %>
    </div>
  </div>
</section>