config/routes.rb
Rails.application.routes.draw do
  resources :empresas do
    member do
      get :agregar_usuario
      post :crear_usuario
    end
  end
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :users, :except => ['show', 'edit', 'update', 'destroy'] do
    resources :simulacions do
      get '/marcar-realizada', to: "simulacions#marcar_realizada", as: "marcar_realizada"
    end
    get '/encuesta_inicial', to: "users#encuesta_inicial", as: "encuesta_inicial"
    post '/encuesta_inicial', to: "users#submit_encuesta_inicial", as: "submit_encuesta_inicial"
    get '/encuesta_final', to: "users#encuesta_final", as: "encuesta_final"
    post '/encuesta_final', to: "users#submit_encuesta_final", as: "submit_encuesta_final"
  end

  get "user/:id", to: "users#show", as: 'show_user'
  get "user/:id/editar", to:"users#edit", as: 'edit_user'
  post "user/:id/editar", to:"users#update", as: 'update_user'
  delete "user/:id/destroy", to:"users#destroy", as: 'destroy_user'
  

  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  get 'experience', to: "pages#experience"
  get 'microagresiones', to: "pages#microagresiones"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"


  #API
  get "api/show_user/:id", to: "api#show_user", as: "api_show_user"
  post "api/simulacion_realizada/:id", to: "api#simulacion_realizada", as: "api_simulacion_realizada"

end

app/models/empresa.rb
class Empresa < ApplicationRecord


    validates :nombre, presence: true
    validates :direccion, presence: true
    validates :comuna, presence: true
    validates :region, presence: true
    validates :rut, presence: false

    has_many :users, dependent: :destroy

    def empleados
        User.where(empresa_id: self.id).where(encargado: false).all
    end

    def encargados
        User.where(empresa_id: self.id).where(encargado: true).all
    end

    def promedio_encuesta_inicial
        promedio = 0
        encuestas_iniciales = []
        self.empleados.each do |empleado|
            if empleado.encuesta_inicial?
                encuestas_iniciales << empleado.encuesta_inicial
            end
        end
        if !encuestas_iniciales.empty?
            cant_encuestas = encuestas_iniciales.length()
            suma = 0
            encuestas_iniciales.each do |encuesta|
                suma += encuesta.porcentaje_bueno
            end
            promedio = suma/cant_encuestas
        else
            -1
        end
    end

    def promedio_encuesta_final
        promedio = 0
        encuestas_finales = []
        self.empleados.each do |empleado|
            if empleado.encuesta_inicial?
                encuestas_finales << empleado.encuesta_final unless empleado.encuesta_final.nil?
            end 
        end
        if !encuestas_finales.empty?
            cant_encuestas = encuestas_finales.length()
            suma = 0
            encuestas_finales.each do |encuesta|
                suma += encuesta.porcentaje_bueno
            end
            promedio = suma/cant_encuestas
        else
            -1
        end
    end

    def tendencia_decisiones
        contador0 = 0
        contador1 = 0
        contador2 = 0

        self.empleados.each do |empleado|
            if empleado.has_simulacion?
                if !empleado.simulaciones.first.decisiones.nil?
                    case empleado.simulaciones.first.decisiones
                    when 0
                        contador0 += 1
                    when 1
                        contador1 += 1
                    when 2
                        contador2 += 1
                    else
                    end
                end
            end
        end

        contadores = [contador0, contador1, contador2]
        contadores.find_index(contadores.max)
        
    end
    
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource
    
    def def new
        @empresa = Empresa.new()
    end
    
    def create
        @empresa = Empresa.new(create_params)
        
        if @empresa.save
            flash[:notice] = "#{@empresa.nombre} ha sido creada con exito"
            redirect_to empresas_path
        else
            flash[:alert] = @empresa.errors.full_messages.join(', ')
            redirect_to new_empresa_path
        end
    end

    def destroy
        @empresa = Empresa.find(params[:id])
        name = @empresa.nombre
        if @empresa.destroy
            flash[:notice] = "#{name} se ha eliminado con exito"
            redirect_to empresas_path
        else
            flash[:alert] = "No se pudo eliminar #{name}"
            redirect_to empresa_path(params[:id])
        end
    end

    def edit
        @empresa = Empresa.find(params[:id])
    end

    def update
        @empresa = Empresa.find(params[:id])
        @empresa.update(create_params)

        if @empresa.save
            flash[:notice] = "#{@empresa.nombre} ha sido actualizada con exito"
            redirect_to empresa_path(id: @empresa.id)
        else
            flash[:alert] = @empresa.errors.full_messages.join(', ')
            redirect_to edit_empresa_path
        end
    end

    def index
        @empresas = Empresa.all
    end

    def show
        @empresa = Empresa.find(params[:id])
    end

    def agregar_usuario
        @empresa = Empresa.find(params[:id])
        @user = User.new()
    end

    def crear_usuario
        @empresa_id = params[:id]
        @user = User.new(user_create_params)
        @user.empresa_id = params[:id]
        if @user.save
            flash[:notice] = "#{@user.nombre} #{@user.apellido} ha sido añadido con exito"
        else
            flash[:alert] = @user.errors.full_messages.join(', ')
            
        end
        redirect_to agregar_usuario_empresa_path
    end

    private

    def create_params
      params.require(:empresa).permit(:nombre, :direccion, :comuna, :oficina, :region)
    end

    def user_create_params
        params.require(:user).permit(:nombre, :email, :apellido, :telefono, :encargado, :password, :password_confirmation)
      end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/agregar_usuario.html.erb
<div class='container'>
  <h2>Añadir Trabajador</h2>
  <br/>

  <%= form_for :user,  url: crear_usuario_empresa_path(@empresa.id) do |f| %>
    
    <div class="field">
      <%= f.label :nombre, class: "form-label"%><br />
      <%= f.text_field :nombre, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :apellido, class: "form-label" %><br />
      <%= f.text_field :apellido, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :email, class: "form-label" %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :telefono, class: "form-label" %><br />
      <%= f.text_field :telefono, autofocus: true, autocomplete: "phone" %>
    </div>

    <div class="field">
      <%= f.label :password, class: "form-label" %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation, class: "form-label" %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>
    <br/>

    <div class="field">
      <%= f.label :encargado, "Encargado: " %>
      <%= f.check_box :encargado, {:class => "form-check-input"}, 'true', 'false' %>
    </div>
    <br/>

    <div class="actions">
      <%= f.submit "Añadir", class: 'btn btn-primary' %>
      <%= link_to "Volver", :back, class: 'btn btn-secondary' %>
    </div>
    <br/>
  <% end %>
</div>

app/views/empresas/edit.html.erb
<div class='container'>

    <h1>Editar Empresa</h1><br/>

    <%= form_for :empresa, url: empresa_path, method: :patch do |f| %>
        <div class="row">

            <div class="col-12">
                <%= f.label :nombre, class: "form-label" %><br>
                <%= f.text_field :nombre, class: "form-control" %>
            </div>

            <div class=" col-12">
                <%= f.label :rut, class: "form-label" %><br>
                <%= f.text_field :rut, class: "form-control" %>
            </div>

            <div class="col-8">
                <%= f.label :direccion, class: "form-label" %><br>
                <%= f.text_field :direccion, class: "form-control" %>
            </div>

            <div class=" col-4">
                <%= f.label :oficina, class: "form-label" %><br>
                <%= f.text_field :oficina, class: "form-control" %>
            </div>

            <div class="col-6">
                <%= f.label :region, class: "form-label" %><br>
                <%= f.select :region, ["Region Metropolitana"], {}, class: "form-control" %>
            </div>
            
            <div class="col-6">
            <%= f.label :comuna, class: "form-label" %><br>
                <%= f.select :comuna, ["Santiago","Conchalí","Huechuraba","Independencia",
                "Quilicura","Recoleta","Renca","Las Condes","Lo Barnechea","Providencia",
                "Vitacura","La Reina","Macul","Ñuñoa","Peñalolén","La Florida","La Granja",
                "El Bosque","La Cisterna","La Pintana","San Ramón","Lo Espejo","Pedro Aguirre Cerda",
                "San Joaquín","San Miguel","Cerrillos","Estación Central","Maipú","Cerro Navia","Lo Prado",
                "Pudahuel","Quinta Normal"],
                {}, class: "form-select" %>
            </div>
            
            <div class="mt-3">
                <%= f.submit "Editar", class: "btn btn-primary " %>
                <%= link_to "Volver", :back, class: 'btn btn-secondary' %>
            </div>
        </div>

    <% end %>
</div>

app/views/empresas/index.html.erb
<div class='container'>
    <h1>Empresas</h1>

    <% @empresas.each do |empresa| %>
        <h2><%= link_to empresa.nombre, empresa_path(empresa.id) %></h2>
        <h4><%= "Direccion: #{empresa.direccion}" %></h4>
        <% if !empresa.oficina.empty? %>
            <h4><%= "Oficina: #{empresa.oficina}" %></h4>
        <%  end %>
        <h4><%= "Comuna: #{empresa.comuna}" %></h4>
        <br/>
    <% end %>

    <div>
        <%= link_to "Añadir Empresa", new_empresa_path, class: 'btn btn-primary'%>
    </div>
</div>

app/views/empresas/new.html.erb
<div class='container'>

    <h1>Añadir Empresa</h1><br/>

    <%= form_for :empresa, url: empresas_path, method: :post do |f| %>
        <div class="row">

            <div class="col-12">
                <%= f.label :nombre, class: "form-label" %><br>
                <%= f.text_field :nombre, class: "form-control" %>
            </div>

            <div class=" col-12">
                <%= f.label :rut, class: "form-label" %><br>
                <%= f.text_field :rut, class: "form-control" %>
            </div>

            <div class="col-8">
                <%= f.label :direccion, class: "form-label" %><br>
                <%= f.text_field :direccion, class: "form-control" %>
            </div>

            <div class=" col-4">
                <%= f.label :oficina, class: "form-label" %><br>
                <%= f.text_field :oficina, class: "form-control" %>
            </div>

            <div class="col-6">
                <%= f.label :region, class: "form-label" %><br>
                <%= f.select :region, ["Region Metropolitana"], {}, class: "form-control" %>
            </div>
            
            <div class="col-6">
            <%= f.label :comuna, class: "form-label" %><br>
                <%= f.select :comuna, ["Santiago","Conchalí","Huechuraba","Independencia",
                "Quilicura","Recoleta","Renca","Las Condes","Lo Barnechea","Providencia",
                "Vitacura","La Reina","Macul","Ñuñoa","Peñalolén","La Florida","La Granja",
                "El Bosque","La Cisterna","La Pintana","San Ramón","Lo Espejo","Pedro Aguirre Cerda",
                "San Joaquín","San Miguel","Cerrillos","Estación Central","Maipú","Cerro Navia","Lo Prado",
                "Pudahuel","Quinta Normal"],
                {}, class: "form-select" %>
            </div>
            
            <div class="mt-3">
                <%= f.submit "Añadir Empresa", class: "btn btn-primary " %>
                <%= link_to "Volver", :back, class: 'btn btn-secondary' %>
            </div>
        </div>

    <% end %>
</div>

app/views/empresas/show.html.erb
<div class='container'>

    <h1><%= @empresa.nombre %></h1>
    <h4><%= "Direccion: #{@empresa.direccion}" %></h4>
    <% if !@empresa.oficina.empty? %>
        <h4><%= "Oficina: #{@empresa.oficina}" %></h4>
    <% end %>
    <h4><%= "Comuna: #{@empresa.comuna}" %></h4>

    <br/>

    <h1>Trabajadores</h1>

    <h2>Encargados</h2>
    <% if @empresa.encargados.empty?%>
        <p>No hay nada aqui todavia</p>
    <% else %>
        <% @empresa.encargados.each do |encargado| %>
            <%= link_to "#{encargado.nombre} #{encargado.apellido} ", show_user_path(encargado.id)%><br/>
        <% end %>
    <% end %>

    <h2>Empleados</h2>
    <% if @empresa.empleados.empty?%>
        <p>No hay nada aqui todavia</p>
    <% else %>
        <% @empresa.empleados.each do |empleado| %>
            <%= link_to "#{empleado.nombre} #{empleado.apellido} ", show_user_path(empleado.id)%><br/>
        <% end %>
    <% end %>

    <br/>
        <div>
            <% if can? :new, User %>
                <%= link_to "Añadir Trabajador", agregar_usuario_empresa_path, class: 'btn btn-primary'%>
            <% end%>

            <% if can? :manage, Empresa %>
                <%= link_to "Volver", :back, class: 'btn btn-secondary' %> <br/>
            <% end %>
            
            <% if can? :edit, Empresa %>
                <%= link_to "Editar", edit_empresa_path, class: 'btn btn-warning' %>
            <% end%>

            <% if can? :delete, Empresa %>
                <div style="display:inline-block;">
                    <%= button_to "Eliminar", empresa_path(@empresa.id), :class=> 'btn btn-danger', method: :delete %>
                </div>
            <% end%>

        </div>
        <br/>
</div>