config/routes.rb
Rails.application.routes.draw do
  resources :empresas do
    member do
      get :agregar_usuario
      post :crear_usuario
    end
  end
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :users, :except => ['show', 'edit', 'update', 'destroy'] do
    resources :simulacions do
      get '/marcar-realizada', to: "simulacions#marcar_realizada", as: "marcar_realizada"
    end
    get '/encuesta_inicial', to: "users#encuesta_inicial", as: "encuesta_inicial"
    post '/encuesta_inicial', to: "users#submit_encuesta_inicial", as: "submit_encuesta_inicial"
    get '/encuesta_final', to: "users#encuesta_final", as: "encuesta_final"
    post '/encuesta_final', to: "users#submit_encuesta_final", as: "submit_encuesta_final"
  end

  get "user/:id", to: "users#show", as: 'show_user'
  get "user/:id/editar", to:"users#edit", as: 'edit_user'
  post "user/:id/editar", to:"users#update", as: 'update_user'
  delete "user/:id/destroy", to:"users#destroy", as: 'destroy_user'
  

  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  get 'experience', to: "pages#experience"
  get 'microagresiones', to: "pages#microagresiones"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"


  #API
  get "api/show_user/:id", to: "api#show_user", as: "api_show_user"
  post "api/simulacion_realizada/:id", to: "api#simulacion_realizada", as: "api_simulacion_realizada"

end

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
  <footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fa fa-twitter"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fa fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fa fa-linkedin"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    SimiBrains © 2022
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_navbar.html.erb
<header id="header-nav">
  <nav class = "nav-container">
    <div class="nav-brand">
      <%= link_to root_path do %>
       <%= image_tag("logo_feelink.png", size: "245x52.5") %>
      <% end  %>
    </div>
    <div id="nav-hamburguer">
      <div class="hamburguer-icon">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
    <ul class ="nav-menu">
      <li> <%= link_to 'Inicio', root_path, class: "#{current_page?(root_path) ? 'link-active' : ''}" %></li>
       <li><%= link_to 'Microagresiones', microagresiones_path, class: "#{current_page?(microagresiones_path) ? 'link-active' : ''}" %></li>
      <li><%= link_to 'Quiénes Somos', about_path, class: "#{current_page?(about_path) ? 'link-active' : ''}" %></li>
      <li><%= link_to 'Contacto', contact_path, class: "#{current_page?(contact_path) ? 'link-active' : ''}" %></li>
      <% if !user_signed_in? %>
        <li><%= link_to 'Iniciar Sesión', new_user_session_path, class: "#{current_page?(new_user_session_path) ? 'link-active' : ''}" %></li>
      <% else %>
        <li><%= link_to 'Mi Perfil', show_user_path(current_user.id), class: "#{current_page?(show_user_path(current_user.id)) ? 'link-active' : ''}" %></li>
        <li><%= link_to 'Experiencia', experience_path(user_id: current_user.id), class: "#{current_page?(experience_path) ? 'link-active' : ''}"%></li>
        <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, class: "#{current_page?(new_user_session_path) ? 'link-active' : ''}" %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_noticias.html.erb
<div class='mb-0'>
  <% if notice %>
    <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
      <strong><%= notice %></strong> 
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  
  <% if alert %>
    <% if alert.instance_of? Array%>
      <% alert.each do |a| %>
        <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
          <strong><%= a %></strong> 
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    <% else %>
      <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
        <strong><%= alert %></strong> 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FeelinkWebsite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta description="Plataforma de tecnología inmersiva para generar empatía en el ambiente laboral">
    <meta keywords="VR Software of microagression">
    <meta author="SimiBrains">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application"%>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%=render 'layouts/navbar'%>
    <%= render 'layouts/noticias' %>
    <main>
     <%= yield %>
    </main>
    <%=render 'layouts/footer'%>
  </body>
</html>